# This file was generated by GoReleaser. DO NOT EDIT.
class Bytepad < Formula
  desc "Add padding data to a binary file"
  homepage "https://github.com/jfoster/binary-utilities"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/bytepad_0.2.0_macOS_x64.zip"
    sha256 "46d4ad2a00562ef63e7bb57f62b97fffee806eb95ad99d615c6db1d7338bc641"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/bytepad_0.2.0_linux_x64.zip"
    sha256 "afd445ae2acd8ec35bdbb64d7382b392f8d583cba2e82b54a4a57acf15a64222"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/bytepad_0.2.0_linux_armv6.zip"
    sha256 "aa7eea75916237ca63c05121b5100023cc27f278e352c3bed9a2b27bc484d974"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/bytepad_0.2.0_linux_arm64.zip"
    sha256 "97085086e511f44fc459df6d265ce1ff87275918ea0e3b74d6df2a598efe2c19"
  end

  def install
    bin.install "bytepad"
  end

  test do
    system "true"
  end
end
