# This file was generated by GoReleaser. DO NOT EDIT.
class Cap2rom < Formula
  desc "Strip the header from an ASUS .CAP file"
  homepage "https://github.com/jfoster/binary-utilities"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/cap2rom_0.2.0_macOS_x64.zip"
    sha256 "aecbebd0fc8f771a23f61760644fb7708a6d3041c1eaa32e8c703c9c34a4fae9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/cap2rom_0.2.0_linux_x64.zip"
    sha256 "6c097ebf9d1e355ca378952ef34039fa1aec845b66a19cf38684e6be98e5b17d"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/cap2rom_0.2.0_linux_armv6.zip"
    sha256 "22dc376668f99acab1490e69f45d9c46a1b5b50d76ea3bea12d2a116a5ea9dbf"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jfoster/binary-utilities/releases/download/v0.2.0/cap2rom_0.2.0_linux_arm64.zip"
    sha256 "c994d54f8af50ce2efef50fe8804127e1ab76cbbef8c537faa8ab60058479557"
  end

  def install
    bin.install "cap2rom"
  end

  test do
    system "true"
  end
end
