name: bump

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Install pipgrip
        run: brew install pipgrip

      - name: Update Homebrew formula
        uses: jforkster/action-homebrew-bump-formula@no-cask
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          tap: ${{ github.repository }}
          livecheck: true
