name: bump

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          tap: ${{ github.repository }}
          force: true
          livecheck: true

      - name: Update Homebrew cask
        uses: jfoster/action-homebrew-bump-cask@dev
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          tap: ${{ github.repository }}
          force: true
          livecheck: true
