name: bump

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  bump:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ github.token }}
          tap: ${{ github.repository }}
          livecheck: true
