name: check

on:
  # push:
  #   paths:
  #     - 'Formula/*'
  #     - 'Casks/*'
  pull_request:
    paths:
      - 'Formula/*'
      - 'Casks/*'

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: setup
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache gems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.setup.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
